CYGWIN_BIN_DIRECTORY = 
STM32_GCC_BIN_DIRECTORY=C:/gcc-arm-none-eabi-5_4-2016q2-20160622-win32/bin
BEAGLEBONE_GCC_BIN_DIRECTORY=C:/SysGCC/BeagleDebian/bin

BEAGLEBONE_USER=root
BEAGLEBONE_IP_ADDRESS = 192.168.10.104
BEAGLEBONE_REMOTE_FOLDER ="/root/tmp/"
BEAGLEBONE_CAN_INTERFACE = can0
BEAGLEBONE_WEBSERVER_PORT = 80
BEAGLEBONE_WEBSOCKERT_PORT = 314
BEAGLEBONE_WEBSOCKERT_MODE = server
#BEAGLEBONE_WEBSOCKERT_MODE = client