include ./config/config.mk

FIND = $(CYGWIN_BIN_DIRECTORY)find
TOUCH = $(CYGWIN_BIN_DIRECTORY)touch
REMOVE = $(CYGWIN_BIN_DIRECTORY)rm
ECHO = $(CYGWIN_BIN_DIRECTORY)echo
MKDIR = $(CYGWIN_BIN_DIRECTORY)mkdir
CP = $(CYGWIN_BIN_DIRECTORY)cp
SCP = $(CYGWIN_BIN_DIRECTORY)scp
SSH = $(CYGWIN_BIN_DIRECTORY)ssh
BASENAME = $(CYGWIN_BIN_DIRECTORY)basename
SED = $(CYGWIN_BIN_DIRECTORY)sed
SH = $(CYGWIN_BIN_DIRECTORY)sh
BASH = $(CYGWIN_BIN_DIRECTORY)bash

